### ISSUE TITLE
Prevent multiple instances from running for a single user

### ISSUE THREAD

**Issue by evilsizorm** [ExLibrisGroup/alma-print-daemon#11]
We are working on setting up some automation so that after patching reboots, the Alma Print Daemon restarts automatically.  While testing this we ended up with multiple instances of the Daemon running at the same time, which either resulted in multiple printouts of each print job, or it resulted in print queue entries being marked as printed, but no paper coming out.

Please add a detection ability to the Daemon so that if it is running, subsequent attempts to run the daemon will show an error, and refuse to start additional instances.

Thanks

**Comment by mgobat** [comment]
Planned for next 2.0 beta release.

**Comment by mgobat** [comment]
This should be fixed in the 2.0 beta.

https://github.com/ExLibrisGroup/alma-print-daemon/releases/tag/v2.0.0-beta-02

**Comment by jdonaghe** [comment]
Does the message !!!!!!!!!Duplicate instance!!!!!!!!! mean there are multiple instances running at the same time? Does the service stop checking for printouts when this happens?

**Comment by mgobat** [comment]
Yes, if this message appears, another copy of the daemon is already running. The second copy should terminate, but the originally running copy should continue checking for printouts.
