### ISSUE TITLE
Don't require installation per user, per workstation

### ISSUE THREAD

**Issue by mgobat** [ExLibrisGroup/alma-print-daemon#13]
It seems, at the moment the Print Daemon has to get installed separately for every user of the PC. It would be much nicer if there were an option to make just one installation (maybe configuring would still be necessary for each user, but even that would be better than, in our case, four single installations)"

**Comment by dregad** [comment]
We came to the same conclusion.  Having a single installation per machine with a user-specific configuration is a much-needed improvement to this.

**Comment by fabian-combox** [comment]
This is highly recommended!

**Comment by fabian-combox** [comment]
What is the status on this? Have you already done anything?

**Comment by mgobat** [comment]
There will be a pre-release version of the Alma Print Daemon with this feature coming soon.

**Comment by mgobat** [comment]
This enhancement, among others, is contained in the Alma Print Daemon 1.3.0-beta release.  
https://github.com/ExLibrisGroup/alma-print-daemon/releases/tag/v1.3.0-beta

**Comment by mgobat** [comment]
Included in release 1.3.
