### ISSUE TITLE
Javascript error: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by evilsizorm** [ExLibrisGroup/alma-print-daemon#15]
This morning the Alma print daemon had crashed with the following message

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property '0' of undefined
at Function.<anonymous>
(C:\Users\Pages\AppData\Local\Programs\alma-print-daemon\resources\app.asar\mai...:47)

**Comment by mgobat** [comment]
Hi Mark...
Did this error occur at startup, or had the app been running a while before the error appeared? 
Thanks...

**Comment by mgobat** [comment]
Mark...
There may be issues when Alma goes down for maintenance, the internet connection fails, etc.  Could you try the [1.2.0-beta](https://github.com/ExLibrisGroup/alma-print-daemon/releases/tag/v.1.2.0-beta) version if you haven't yet?

**Comment by evilsizorm** [comment]
Thanks for making me aware of this version, we will install it next week.

Mark

**Comment by mgobat** [comment]
This defect should be repaired in version 1.2.0.
