### ISSUE TITLE
Support for grayscale printing

### ISSUE THREAD

**Issue by Waynelam** [ExLibrisGroup/alma-print-daemon#17]
Currently the print function support only color printing. It would be better for this to be configurable. It should be able to be done via  mainWindow.webContents.print

Details:
https://www.electronjs.org/docs/api/web-contents#contentsprintoptions-callback

**Comment by mgobat** [comment]
This enhancement, among others, is contained in the Alma Print Daemon 1.3.0-beta release.  
https://github.com/ExLibrisGroup/alma-print-daemon/releases/tag/v1.3.0-beta

**Comment by mgobat** [comment]
Included in version 1.3.
