### ISSUE TITLE
Interval in minutes - adjust to seconds

### ISSUE THREAD

**Issue by davjak** [ExLibrisGroup/alma-print-daemon#18]
We would like to use the print daemon however with the interval set to minutes there is a possible 60 second delay and a wait for staff to process hold slips. with the option changed to seconds we could set it to a much quicker check and therefore print suiting our needs

**Comment by mgobat** [comment]
You should be able to use a decimal value (ie: .25) for the "Interval in minutes", though I'm not sure how well it will perform under heavy load.  Please try it, if you like, and report back here.

**Comment by davjak** [comment]
Thanks @mgobat 
I will pass this onto our team and see how we go

**Comment by mgobat** [comment]
David, has the decimal value helped with this problem?  Thanks...

**Comment by davjak** [comment]
Hi mgobat 
Unfortunately this has been put on the back burner by our IT department until such a time where they can invest more time to fully test and implement so I'm unable to report back at this time if it worked using decimal value

**Comment by mgobat** [comment]
The readme was updated to reflect that decimal values are possible in the interval field.
