### ISSUE TITLE
Duplicate print outs on occasion.  

### ISSUE THREAD

**Issue by prbutler** [ExLibrisGroup/alma-print-daemon#23]
I've received a report from one circ location that on occasion a circ receipt or transit slip will print out twice, creating a duplicate copy. This has happened to different staff at the same location. The printouts queue in Alma only shows one instance of the print job, so I am thinking it is caused by some aspect of the daemon. We have a pretty standard daemon setup, though we do have "Interval in minutes" set to .5 (30 seconds). I have not been able to recreate this in the Alma Sandbox. This issue is not burdensome now due to the infrequency, but I thought I should report it. Any thoughts? 

Thanks for your time.
Cheers, Paul
LDADS-18523

**Comment by mgobat** [comment]
This may be a result of the quick time interval you have set; not sure until I take a look at the code.  I'm guessing that with the quick time interval, the daemon may not have had a chance to mark all documents from one batch as "printed" before requesting the next batch.

I'll flag this as a defect, but keep it lower priority for now.  Thanks for reporting!

**Comment by prbutler** [comment]
We had another round of duplicate prints on 2021-02-15. We have several circ desks setup using the daemon, but again it happened at only the one desk. Though this happens to be our busiest circ desk. Only single instances of the jobs appear in the printout queue. Different user than the other times this has happened. To confirm, can the "Interval in minutes" field handle .75? Any other suggestions? Thanks!

**Comment by jdonaghe** [comment]
We are also having duplicate slips printing from one of our circ desks. The issue began on 28th of May and is still continuing.

We are using v1.3 and have our interval set to 0.25.

**Comment by mgobat** [comment]
@jdonaghe and @prbutler, any chance you could try the version 2.0 beta on one workstation exhibiting this problem? We modified the code considerably and hope that the duplicates problem is solved in 2.0.  

https://github.com/ExLibrisGroup/alma-print-daemon/releases/tag/untagged-f928860a5c769165bbdf

**Comment by jdonaghe** [comment]
We updated to v2.0 and have not had any reports of duplicate slips printing.

**Comment by mgobat** [comment]
Customers haven't had this problem with the 2.0 alpha version.

https://github.com/ExLibrisGroup/alma-print-daemon/releases/tag/v2.0.0-beta-02
