### ISSUE TITLE
Print Daemon 2.0-beta issues

### ISSUE THREAD

**Issue by DanielaDoerr** [ExLibrisGroup/alma-print-daemon#27]
We installed PrintDaemon 2.0-beta and experienced some issues:

- It was impossible to change the printer format. It remained in the landscape printout. 
- Once created “Printer Profiles” could not be deleted.
- When trying to select a printer, all were selected.

**Comment by mgobat** [comment]
Hmmmm....those are some serious issues.  Could you possibly email me your alma-print-config.json file?  mark.gobat@exlibrisgroup.com

Also, could you rename the file and try setting the configuration again?  Thanks.

**Comment by DanielaDoerr** [comment]
With the new release 2.0.0-beta-02 the software does its job flawlessly. Everything ist working fine. Thanks for the quick fix.

**Comment by mgobat** [comment]
Thanks for testing, @DanielaDoerr.
