### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by jdonaghe** [ExLibrisGroup/alma-print-daemon#31]
We are seeing a recurring error in the logs since the 13th of May. Here's an extract:

`Error on 2021-05-31T05:02:09.944Z':  An error occurred communicating with Alma:  {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"117.20.42.137","port":443}
Error on 2021-05-31T05:03:01.762Z':  An error occurred communicating with Alma:  {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"117.20.42.137","port":443}
Error on 2021-05-31T05:03:37.820Z':  An error occurred communicating with Alma:  {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"117.20.42.137","port":443}`

We are running v1.3 and have the interval set to 0.25.

**Comment by mgobat** [comment]
@jdonaghe, does the Alma Print Daemon eventually start working again, or do you have to stop the Alma Print Daemon and restart it to get rid of the timeout error? Thanks.

**Comment by jdonaghe** [comment]
It eventually starts to work again. Thanks

**Comment by mgobat** [comment]
@jdonaghe, then I think its working as expected. If it ever doesn't start working again after the timeout error, then we probably have an issue. Thanks!
