### ISSUE TITLE
Documentation request: building an alma-print-daemon.Setup.x.x.x.exe

### ISSUE THREAD

**Issue by Jimadine** [ExLibrisGroup/alma-print-daemon#40]
I've forked the alma-print-daemon repo so that I can make some changes for our local needs. One thing I'm unsure about is how to build a package for my target platform (Windows x64). Should I use [https://github.com/electron/electron-packager](https://github.com/electron/electron-packager)? Anything particular to alma-print-daemon that I should be aware of before attempting this?

**Comment by mgobat** [comment]
Ex Libris uses [electron-builder](https://www.electron.build/) to build the Alma Print Daemon packages. Nothing special is done beyond signing the application to prevent application security issues during installation.
