### ISSUE TITLE
Configuration options missing

### ISSUE THREAD

**Issue by kremke** [ExLibrisGroup/alma-print-daemon#41]
Hi,

I wonder if this is the same issue ad described in the now closed issue #34.  At first I installed the latest pre-release but when I try to configure the daemon I don't get the same options as shown in the blog or in Yoel Kortick's video.  I have checked and re-checked that the api key I created is for the required permissions and the print daemon says my key is valid.  I have also tried the api key out in the api console and there I get a list of printers so I assume the problem isn't with the api key.

But here I'm stuck, the configuration window looks like this:

![image](https://user-images.githubusercontent.com/76584888/151701568-29b02777-0779-4561-b9e1-ac23388f8851.png)
Everything is grayed out and the only way to close the window is with ALT-f4.

I tried uninstalling the pre-release and installing the latest stable version but the results are the same.  Attached is the logfile that you asked for in issue #34.  I checked, and there is no .json configuration file, which makes sense since I haven't been able to input any options, except for the api key.

I also tried this on a Virtual machine running Windows 11 and got the same result.  Is there any reason you can think of why I don't get the option to add printers?

Regards,

Helgi Steindal
[log.alma-print-daemon.2022-1-30.txt](https://github.com/ExLibrisGroup/alma-print-daemon/files/7965978/log.alma-print-daemon.2022-1-30.txt)

**Comment by mgobat** [comment]
@kremke, is at least one of your printers in Alma defined to be a "Printout Queue"? Only printers with this flag turned on are eligible for configuration in the Alma Print Daemon.

**Comment by kremke** [comment]
Hi Mark,

It is my understanding that all the printers in the IZ should be print queues.  A print slip shows up in Alma as being in a print queue:
![image](https://user-images.githubusercontent.com/76584888/151826262-526fb06d-3613-48bd-a748-2fdad083ab85.png)

Since I haven't passed the sysadmin test yet, I don't have access to the printer configuration so I can't double check that all printers are in fact configured as a printer queue.  But the AKRAV printer was configured exactly like other printers in the IZ so I assume that if that printer is correctly configured then rest of the printers should be as well.  But then, again, assuming things is  probably not the best way to debug problems.  Gudula Holzheid, Christine Godard and Chiara Consonni have configured this for us.  I can ask them to check -- or do you want to contact them yourself?

Regards, 

Helgi

**Comment by kremke** [comment]
Hi again Mark,

I used the api to get info on the printers, at least the first 10 printers had <printout_queue>true</printout_queue> 

Regards,

Helgi

**Comment by mgobat** [comment]
@kremke, that was smart! Thank you. Officially a bug of some sort.  :)

**Comment by mgobat** [comment]
@kremke, could you share your API key with me off Github?  email: mark.gobat@exlibrisgroup.com.  Thanks.

**Comment by mgobat** [comment]
Believe fixed in version 2.0.0-beta-03.
