### ISSUE TITLE
Allow update of printer profiles

### ISSUE THREAD

**Issue by dregad** [ExLibrisGroup/alma-print-daemon#43]
Currently (2.0.0-beta-03) the configuration dialog does not allow the user to edit existing printer profiles. To make a change, the only way is to delete the profile, then add it back.

This was not much of a problem before, but with the additional settings (paper format, margins, etc) that sometimes require some tweaking, it's becoming more of a hassle.

**Comment by dregad** [comment]
I tested the edit functionality this morning on 2.1.0-beta2 release and it seems to work as expected.

That being said, considering #44 I'm not sure what is actually happening to the profiles when edited by multiple users. I'll perform some additional tests in coordination with a colleague later and get back to you.

**Comment by mgobat** [comment]
@dregad, thank you for testing this enhancement. Each user should have their own alma-print-config.json file in C:\Users\<username>\AppData\Roaming\alma-print-daemon.

**Comment by mgobat** [comment]
Editing existing printer profiles available in version 2.1.0.
