### ISSUE TITLE
Decreased font size with Alma Print Daemon 2.0.0 

### ISSUE THREAD

**Issue by prbutler** [ExLibrisGroup/alma-print-daemon#53]
After updating the Alma Print Daemon from v1.3.1 to v2.0.0 the font size for our printed slips is tiny, nearly impossible to read. We are using an EPSON TM-T88IV thermal receipt printer with Windows 10. I've tested with various paper formats, and while none of them seem to fix the issue, the A5 format does slightly increase the font size. The border settings seem to work okay when tested. When printing to other printers the font seems fine. I've tested a few printer settings for the thermal printer, but have not found anything that helps. 

To compound this issue at our circ desks the v2.0.0 update is being applied automatically. 

The thermal printer paper size width is 3 1/8" or ~80mm, so much closer to A7, so I think the issue is having more options for the paper format. 

Cheers, Paul

**Comment by Aavalaakso** [comment]
We have the same problem. We are using Star branded Laber Printers and now it gives us 1-2 meter long recipes. Please remove that forced paper size selection. It worked before this update.

**Comment by janeicec** [comment]
The v2.0.0 update automatically being applied is also causing us problems. We also use Epson TM-T88V thermal receipt printers and are running into the tiny font problem. In my experience these thermal printers are fairly commonly used (at least in the US), especially at circ desks, and use a paper size (80mm width) that needs to be included in Print Daemon's configurations. In our case, we are only using Print Daemon for printing hold and transit slips on these thermal receipt printers so without a fix we'd have to revert to using the less optimal Quick Print in Alma. 

If adding page sizes or removing the forced paper size selection can't be done, then we need an easy way to rollback to v1.3.1 and avoid the automatic updating.

**Comment by mgobat** [comment]
If you re-install 1.3.1, you should no longer be forced to upgrade to 2.0.0.

**Comment by janeicec** [comment]
Thank you!

**Comment by Aavalaakso** [comment]
> If you re-install 1.3.1, you should no longer be forced to upgrade to 2.0.0.

Thanks this did the trick I installed 1.3.1. over the 2.0.0. It is not force updating anymore.

**Comment by prbutler** [comment]
I can confirm re-installing 1.3.1 resolved the issue for now. Like others, I would love to see v2.1.0 accommodate thermal paper form factor since it is pretty common. Thank you!

**Comment by mgobat** [comment]
@prbutler, @janeicec...you both mention 80mm as the width...what is the height of the labels? Thanks.

**Comment by janeicec** [comment]
Our printer preferences have it as 80mm x 297mm

**Comment by Aavalaakso** [comment]
80mm but height depends of the print..

**Comment by prbutler** [comment]
Like @janeicec, our printer preference is also set to 80mm x 297mm, but as @Aavalaakso suggests the height is variable based on the print job. Thanks @mgobat!

**Comment by mgobat** [comment]
Release 2.1.0-beta1 adds the ability to define a custom format. Please see https://github.com/ExLibrisGroup/alma-print-daemon/releases/tag/v2.1.0-beta1. Pre-release, please test before rolling out to everyone. Impossible for us to test on all the different label-specific printers out there. Please report any issues as new issues in GitHub.

**Comment by Aavalaakso** [comment]
1.3.1 force updated back to the 2.0.0 again. i re-installed 1.3.1 back.

**Comment by Aavalaakso** [comment]
> Release 2.1.0-beta1 adds the ability to define a custom format. Please see https://github.com/ExLibrisGroup/alma-print-daemon/releases/tag/v2.1.0-beta1. Pre-release, please test before rolling out to everyone. Impossible for us to test on all the different label-specific printers out there. Please report any issues as new issues in GitHub.

The problem is that we don't know the height of the print. Thermal printers prints all what is needed and then automatically cuts the paper. We can't insert fixed Height like a3, a4 and a5 are fixed sizes. Thermal printers are scroll of paper and printer cuts after all printed.

If this is not possible then please make 1.3.1 version that it wont force update to the latest version.

**Comment by prbutler** [comment]
@Aavalaakso as for the 2.1.0-beta1 update, so for in my testing setting the Page Width to 80 and the Page Height to 297 seems to work for checkout, transit, and hold slips for us. Setting the height 297 does not impact slips lengths and automatic paper cutting. 

No reports yet of 1.3.1 prompting for an update.

**Comment by mgobat** [comment]
1.31. should not be updating, as version 2.0.0 is now flagged as "Pre-release", and the latest 2.1.0-beta1 is "Pre-release", too.

**Comment by Aavalaakso** [comment]
Hi. I installed 2.1.0 beta1 and set custom 80x297. Today I received information from library that it printed normally. I will keep my eye on this how it works.

**Comment by Aavalaakso** [comment]
Hi. Well this morning they told that it printed long white paper but text was normal size. I totally removed 2.x version off and installed 1.3.1. They said it works normally when using 1.3.1. Printer cuts the paper after everything is printed. It would take a lot of time trying the find fixed paper length that works and then it wont work if there are more things to print than paper size is.

Is it possible to make that there is option to select "paper size: undefined"? Because the printer it self knows the limits when it prints. It is the way how all thermal printers works and then cuts the paper automatically.

**Comment by mgobat** [comment]
@Aavalaakso, thanks for that additional feedback. Let me do some experimenting with not setting a page size. I'm going to create a new issue for this, though.

**Comment by mgobat** [comment]
Please see https://github.com/ExLibrisGroup/alma-print-daemon/releases/tag/v2.1.0-beta2. We've restored the old method of printing from version 1.3.1 if not running this new version as a Windows service. If anyone is adventurous enough to try it out (on a single workstation), we'd appreciate any feedback. Thanks.
