### ISSUE TITLE
2.1.0 beta Releases / tags are listed out of order

### ISSUE THREAD

**Issue by dregad** [ExLibrisGroup/alma-print-daemon#60]
Releases are currently listed in the following order
![image](https://user-images.githubusercontent.com/449891/188836174-8a17e606-ed60-4ea5-be56-410f92d30af5.png)

At first I thought this is not a huge deal, just somewhat confusing - as I downloaded the "latest" pre-release (beta.2) only to find out afterwards that there was a beta.3 available.

Then I checked in more detail, and found out that v2.1.0-beta3 is actually the same as v2.0.0 and master 

$ git log  --graph --oneline v2.1.0-beta2
* 67fba33 (tag: v2.1.0-beta2) Use pre-2.0 method of printing if not running as a Windows service
* 8ea2f90 (tag: v2.1.0-beta1) 2.1.0
* eace7a1 (HEAD -> master, tag: v2.1.0-beta3, tag: v2.0.0, origin/master, origin/HEAD) Add Service functionality (#47)
* f10f2a8 (tag: v1.3.1) Fix auto update defect.

So in fact the **v2.1.0-beta3 tag is wrong** - maybe it was meant to point at commit 11523c97 (head of 2.1.0 branch) ?

Please fix

**Comment by mgobat** [comment]
@dregad, yes, I created the 2.1.0-beta3 release pointing to the wrong commit. You are much more experienced with GitHub than I. Once we move 2.1.0 out of beta, I'll clean up the releases.
