### ISSUE TITLE
Latest Release should be 2.0.0 

### ISSUE THREAD

**Issue by dregad** [ExLibrisGroup/alma-print-daemon#61]
While looking at Releases as I reported #60, I also realized that **2.0.0 is marked as *pre-release***, so https://github.com/ExLibrisGroup/alma-print-daemon/releases/latest still points to 1.3.1

I guess this is not intentional, the _This is a pre-release_ checkbox should be un-ticked

**Comment by mgobat** [comment]
2.0.0 was re-labeled as a pre-release so it isn't forced on users who preferred the way 1.3.1 printing worked (version 1.3.1 will autoupdate to the latest release).
