### ISSUE TITLE
Log files location and naming

### ISSUE THREAD

**Issue by dregad** [ExLibrisGroup/alma-print-daemon#76]
Currently (2.0.0-beta-02) , the program stores its logs in `%APPDATA%` (`C:\Users\xxx\AppData\Roaming\alma-print-daemon`)

Considering that there is an existing `logs` directory there, IMO it would make sense to store the daily log files there as well.

I would also suggest to rename the log files. Currently they are named like `log.alma-print-daemon.YYYY-M-D`. It would make more sense if they were named like `alma-print-daemon.YYYY-MM-DD.log`, for the following benefits:

- Using a common file extension, allows to open them easily from explorer with a double-click - currently, we get this: 

  ![image](https://github.com/ExLibrisGroup/alma-print-daemon/assets/449891/196be058-d586-4047-9b4f-b5c0aafd9555)

- Use `MM-DD` instead of `M-D` for date formatting would allow correct sorting of the files (see example output of DIR command for current naming)

      01.05.2023  16:42            37 320 log.alma-print-daemon.2023-5-1
      10.05.2023  17:24            37 320 log.alma-print-daemon.2023-5-10
      11.05.2023  11:53            37 320 log.alma-print-daemon.2023-5-11
      02.05.2023  09:49            37 320 log.alma-print-daemon.2023-5-2

**Comment by mgobat** [comment]
The first beta version with this feature is available now at https://github.com/ExLibrisGroup/alma-print-daemon/releases/tag/v2.2.0-beta-03.

Note that only the log file names have changed as suggested. The location of the log files remains the same, except in a single configuration file installation.

**Comment by dregad** [comment]
I have tested today, and confirm that the new naming is effective, and the log files are saved in the expected location (local user's profile, or global config directory). 

Thank you !
