### ISSUE TITLE
Enable 1 Alma Print Daemon to Serve Multiple Printers

### ISSUE THREAD

**Issue by evilsizorm** [ExLibrisGroup/alma-print-daemon#8]
I am thankful that the Alma Printouts Queue and Print Daemon exists. The free email service bundled with our printers has proven to be unreliable at times.

However it is unfortunate that 1 PC can only run 1 instance of the Print Daemon software. So to map multiple Alma printers to multiple local printers requires running the Daemon on multiple servers (we use VMs rather than end user PCs).

The enhancement I am requesting is for this software to be able to map multiple Alma printers each to their own separate local printer. For example

- Alma Printer Main Circ Desk -> Local Printer BLDGAFLR2-7
- Alma Printer Rare Book Circ Desk -> Local Printer BLDGBFLR1-3
and so on.

One instance of Printer Daemon serving all our queue to printer mapping needs.

Thanks,
Mark

**Comment by mgobat** [comment]
Let me confirm what you are asking for here:
Given a list of available Alma printers that are print queues:

1. Allow selection of an Alma printer.
2. Allow selection of a local/network printer to service the selected Alma printer.
3. Set any preferences for that local printer (portrait/landscape, color/greyscale).
4. Save the Alma/local printer pair as a printer profile.
5. Route printouts from any selected Alma printer to the local/network printer as indicated in the printer profiles.

Defining a new Alma/Local printer profile:
![almaprinters](https://user-images.githubusercontent.com/45852490/102114655-1220e580-3e00-11eb-88ba-073a391efae1.png)

Displaying saved Alma/Local printer profiles:
![almaprinterprofiles](https://user-images.githubusercontent.com/45852490/102115209-de928b00-3e00-11eb-85f6-a6a7126f4504.png)


Feedback/thoughts from anyone?

**Comment by evilsizorm** [comment]
Mark this looks very good.  A couple of thoughts/confirmations

- If implemented as depicted, this one Daemon would be able to fetch and print for each of the profiles configured, correct?
- In the Printer Profiles section I see the ability to Add and Remove, which will work great, if edit could be an option that would be nice
- In the Select Alma Printers image, it looks like it would be possible to map multiple Alma Printouts Queues to a local Printer, we don't currently have that scenario but I could imagine it being helpful in the future if we did (or we could just add two profiles targeting the same local printer)

Thanks,
Mark

**Comment by mgobat** [comment]
Thanks for the feedback, Mark!

1. Yes, one installation of the Daemon would fetch printouts from the Alma Printer specified in each Printer Profile and print to the Printer Profile's physical local/network printer.
2. Yes, "edit" would be nice.  Maybe in the subsequent release.
3. Yes, that is how it works in the current version, too.  You can select as many Alma Printer Queues as you like to be serviced by one local/network printer.

**Comment by mgobat** [comment]
This enhancement, among others, is contained in the Alma Print Daemon 1.3.0-beta release.  
https://github.com/ExLibrisGroup/alma-print-daemon/releases/tag/v1.3.0-beta

**Comment by mgobat** [comment]
Hi Mark....

Have the multiple printer profiles in 1.3.0-beta been working well for you? Thanks....

-mark

**Comment by evilsizorm** [comment]
Thanks for following up, yes the new feature is working well for us.

Mark
