### ISSUE TITLE
Add log directory location to the wiki page

### ISSUE THREAD

**Issue by enettifee** [ExLibrisGroup/alma-print-daemon#85]
It would be helpful to add the location of logs to the wiki help information (C:\Users\<<USERNAME>>\AppData\Roaming\alma-print-daemon). I was running into issues with some local testing and needed to find where the logs were, and got a bit stumped before finding the location (and the logs ended up pointing me to a solution.) So I think it would help to just specify the directory in the wiki content for future users.

**Comment by mgobat** [comment]
@enettifee, thanks for the excellent suggestion. Sorry the information wasn't there when you needed it.

**Comment by enettifee** [comment]
No problem @mgobat, thanks for adding.
